In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/kaggle/input/titanic-datasets/titanic.csv")
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [ ]:
df.shape

(418, 12)

In [ ]:
df['Age'].max(), df['Age'].min()

(76.0, 0.17)

In [ ]:
df['Age'].describe()

count    332.000000
mean      30.272590
std       14.181209
min        0.170000
25%       21.000000
50%       27.000000
75%       39.000000
max       76.000000
Name: Age, dtype: float64

In [ ]:
df['Age'].fillna(value=24.044, inplace=True)

In [ ]:
df = df.drop("Cabin", axis=1)

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Embarked  
0   330911   7.8292        Q  
1   363272   7.0000        S  
2   240276   9.6875        Q  
3   315154   8.6625        S  
4  3101298  12.2875        S

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Embarked']= label_encoder.fit_transform(df['Embarked'])
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare  Embarked  
0   330911   7.8292         1  
1   363272   7.0000         2  
2   240276   9.6875         1  
3   315154   8.6625         2  
4  3101298  12.2875         2

In [ ]:
df = df.drop(["Name", "Ticket"], axis=1)

In [ ]:

df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892         0       3    1  34.5      0      0   7.8292         1
1          893         1       3    0  47.0      1      0   7.0000         2
2          894         0       2    1  62.0      0      0   9.6875         1
3          895         0       3    1  27.0      0      0   8.6625         2
4          896         1       3    0  22.0      1      1  12.2875         2

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           1
Embarked       0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df.head()

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0          892         0       3    1  34.5      0      0   7.8292         1
1          893         1       3    0  47.0      1      0   7.0000         2
2          894         0       2    1  62.0      0      0   9.6875         1
3          895         0       3    1  27.0      0      0   8.6625         2
4          896         1       3    0  22.0      1      1  12.2875         2

In [ ]:
df.corr()

PassengerId  Survived    Pclass       Sex       Age     SibSp  \
PassengerId     1.000000 -0.024117 -0.025800  0.024117 -0.029137  0.003259   
Survived       -0.024117  1.000000 -0.107203 -1.000000  0.019683  0.099136   
Pclass         -0.025800 -0.107203  1.000000  0.107203 -0.496738  0.002136   
Sex             0.024117 -1.000000  0.107203  1.000000 -0.019683 -0.099136   
Age            -0.029137  0.019683 -0.496738 -0.019683  1.000000 -0.060687   
SibSp           0.003259  0.099136  0.002136 -0.099136 -0.060687  1.000000   
Parch           0.042650  0.158534  0.019581 -0.158534 -0.040091  0.306566   
Fare            0.008211  0.191514 -0.577147 -0.191514  0.359879  0.171539   
Embarked        0.041521 -0.075106  0.226856  0.075106 -0.143126  0.053595   

                Parch      Fare  Embarked  
PassengerId  0.042650  0.008211  0.041521  
Survived     0.158534  0.191514 -0.075106  
Pclass       0.019581 -0.577147  0.226856  
Sex         -0.158534 -0.191514  0.075106  
Age         -0.040091  0.359879 -0.143126  
SibSp        0.306566  0.171539  0.053595  
Parch        1.000000  0.230046  0.055293  
Fare         0.230046  1.000000 -0.257183  
Embarked     0.055293 -0.257183  1.000000

In [ ]:
X = df[["Pclass", "Sex", "SibSp", "Parch", "Fare", "Embarked"]].values
Y = df["Survived"].values
X, Y

(array([[ 3.    ,  1.    ,  0.    ,  0.    ,  7.8292,  1.    ],
        [ 3.    ,  0.    ,  1.    ,  0.    ,  7.    ,  2.    ],
        [ 2.    ,  1.    ,  0.    ,  0.    ,  9.6875,  1.    ],
        ...,
        [ 3.    ,  1.    ,  0.    ,  0.    ,  7.25  ,  2.    ],
        [ 3.    ,  1.    ,  0.    ,  0.    ,  8.05  ,  2.    ],
        [ 3.    ,  1.    ,  1.    ,  1.    , 22.3583,  0.    ]]),
 array([0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
        1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
        0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

In [ ]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
Y_preds = model.predict(X_test)

In [ ]:
Y_preds

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(Y_test, Y_preds)

In [ ]:
score

1.0